# Linux
STAGING_DIR     =
BIN             =
LIBEXEC         =
CC              = gcc
CXX             = g++
STRIP           = strip
RM              = rm
AR              = ar
RANLIB          = ranlib
PLATFORM        = linux
TARGET_DIR      = .
MY_CFLAGS       =

include rules.mk
